title: Abhishek sinha # your name (or website title) here
logo: "/images/cropped_pic.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <be> Senior Data Analyst with 2+ years of commercial experience in data science, analytics, strategy and sales and an upcoming master's graduate student in Data Analytics engineering from Northeastern University, Boston. Previously at Ganit Inc.
  <br><br>
  <a href="https://www.linkedin.com/in/abhishek-kumar-sinha-1aa0b6188">View My LinkedIn Profile</a> 
  
remote_theme: jekyll-theme-minimal ##pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: ----- # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
